server:
  port: 8004

spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: xxxxx
    password: xxxxx
    url: jdbc:mysql://xxx.xxx.xx.xxx:3306/jeeplus_schema?useUnicode=true&characterEncoding=utf-8

  jpa:
    show-sql: true

  thymeleaf:
      cache: false
      mode: LEGACYHTML5


