server:
  port: 8004

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: YEKDBTEST
    password: test123456
    url: jdbc:mysql://192.168.80.174:3306/jeeplus_schema?useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true



##  username: YEKDB
##  password: YEK,123456
##  url: jdbc:mysql://192.168.80.174:3306/XLSTOHDDB?useUnicode=true&characterEncoding=utf-8
